### PR TITLE
Reorganize modules, fix circle drawing

### LINKED ISSUE #16: 100% CPU when idle
Profiling didn't reveal anything interesting, so it's going to be difficult to nail down.

### PR DESCRIPTION
**Pull request by int-index**
1. Fix circle drawing (cc @v0d1ch — `Cairo.arc` takes radians, not degrees, so `180` instead of `2 * pi` meant that the circle was drawn 28 times over). Closes #16 
2. Drop the dependency on `reflection` (implement inline).
3. Add a `runLayout` combinator.
4. Refactor the GTK example: move `Phaser` to its own module, auto-generate keycode patterns with TH, add transformation matrix caching.

### CODE REVIEW

File: cairo/src/Slay/Cairo.hs [hunk 1]
```diff
@@ -122,5 +122,5 @@ instance RenderElement g (PrimCurve g) where
 instance RenderElement g (PrimCircle g)   where
   renderElement (PrimCircle cc c) getG (Offset x y) = do
       setSourceColor $ getG cc
-      Cairo.arc (toSigned c + x) (toSigned c + y) (toSigned c) 0 180
+      Cairo.arc (toSigned c + x) (toSigned c + y) (toSigned c) 0 (2 * pi)
```
Comment (hithroc) [inline cairo/src/Slay/Cairo.hs]: 180 degrees is π/2, not 2π

Comment (int-index) [reply cairo/src/Slay/Cairo.hs]: A circle is 2pi

Comment (hithroc) [reply cairo/src/Slay/Cairo.hs]: Okay, I thought you needed a half-circle judging by the original code.
